name: Deploy To Server
on:
  push:
    branches:
      - master
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.14.6"
      - name: Install Vips
        run: |
          wget https://github.com/libvips/libvips/releases/download/v8.10.2/vips-8.10.2.tar.gz
          tar xf vips-8.10.2.tar.gz
          cd vips-8.10.2.tar.gz
          ./configure
          make
          sudo make install
          sudo ldconfig
          cd ..
      - name: Build File
        run: GOOS=linux GOARCH=amd64 go build
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./backend"
          target: "api.iduslab.xyz"
      - name: Setting to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd api.iduslab.xyz
            [ -e main ] && rm main
            mv backend main
            if [[ $(pm2 list | grep api.iduslab.xyz) ]]; then pm2 restart api.iduslab.xyz; else pm2 start ./main -n api.iduslab.xyz; fi
